version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
environment:
  VisualStudioVersion: 14.0
  GeneratePInvokesTxt: true
cache:
- '%USERPROFILE%\.nuget\packages'
before_build:
- ps: nuget restore src
build:
  project: src\pinvoke.sln
  verbosity: minimal
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
- path: bin\**\*.pinvokes.txt
  name: PInvoke method coverage
- path: bin\**\*.exports.txt
  name: Exported methods
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/c4d61fc5002e9a62a22f
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
